version: "3.8"

volumes:
  n8n_data:

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secret
      - GENERIC_TIMEZONE=America/Guayaquil
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
